#' Fisher's Exact Test for Positivity Calls
#'
#' @description
#' Performs a row-wise Fisher's Exact Test comparing stimulated samples to
#' their negative controls, followed by a Holm-Bonferroni p-value adjustment.
#'
#' @param x A data.frame or tibble. Must contain columns generated by
#' \code{calculate_bg_adjustment} (CYTNUM, NSUB, CYTNUM_NEG, NSUB_NEG).
#' @param alpha Numeric. The significance threshold for the adjusted p-value.
#' Default is \code{0.00001}.
#' @param group_cols Vecteur of characters. Columns used to group data for the
#' p-value adjustment (multiplicity correction).
#' @param adjustment Character. The correction method passed to \code{stats::p.adjust}.
#' Default is \code{"holm"}. Options include "bonferroni", "BH", "fdr", etc.
#'
#' @return A data.frame with additional columns:
#' \item{raw_p}{Original p-value from Fisher's Exact Test}
#' \item{num_tests}{Number of tests performed within each group}
#' \item{adjvar}{A string listing the variables used for adjustment grouping}
#' \item{adjp}{P-value adjusted using the specified \code{adjustment} method}
#' \item{response}{Binary indicator (1 for positive, 0 for negative)}
#'
#' @export
#'
#' @import dplyr
#' @importFrom stats fisher.test p.adjust
call_positivity <- function(x,
                            alpha = 0.00001,
                            group_cols = c("PROTOCOL", "LABID", "ASSAYID", "PTID", "VISITNO", "SUBSET"),
                            adjustment = "holm") {

  # 1. Row-wise Fisher's Exact Test
  # We use mapply for efficiency over a for-loop
  x$raw_p <- mapply(function(x_ant, n_ant_total, x_neg, n_neg_total) {

    # Calculate Non-positive counts (N)
    N_ant <- n_ant_total - x_ant
    N_neg <- n_neg_total - x_neg

    # Validation: Fisher's requires non-negative values and non-empty backgrounds
    if (is.na(N_neg) || is.na(N_ant) || N_ant < 0 || N_neg < 0) {
      return(NA_real_)
    }

    # Construct 2x2 contingency table
    #           Positives | Negatives
    # Stim     [ x_ant    | N_ant ]
    # NegCtrl  [ x_neg    | N_neg ]
    m <- matrix(c(x_ant, N_ant, x_neg, N_neg), ncol = 2, byrow = FALSE)

    return(stats::fisher.test(m, alternative = "greater")$p.value)

  }, x$CYTNUM, x$NSUB, x$CYTNUM_NEG, x$NSUB_NEG)

  # 2. Multiplicity Correction (Holm)
  result <- x %>%
    dplyr::group_by(dplyr::across(dplyr::all_of(group_cols))) %>%
    dplyr::mutate(
      num_tests = dplyr::n(),
      adjvar    = paste(tolower(group_cols), collapse = ","),
      adjp      = stats::p.adjust(raw_p, method = adjustment),
      response  = ifelse(!is.na(adjp) & adjp < alpha, 1, 0)
    ) %>%
    dplyr::ungroup()

  return(result)
}

